name: Build & Deploy (GitHub Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # once per day

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set env defaults
        shell: bash
        run: |
          # Your publication + feed
          FEED="${SUBSTACK_FEED:-${{ secrets.SUBSTACK_FEED }}}"
          if [ -z "$FEED" ]; then FEED="${{ vars.SUBSTACK_FEED }}"; fi
          if [ -z "$FEED" ]; then FEED="https://versesvibez.substack.com/feed"; fi
          echo "SUBSTACK_FEED=$FEED" >> "$GITHUB_ENV"

          PUB="${PUBLIC_SUBSTACK_URL:-${{ secrets.PUBLIC_SUBSTACK_URL }}}"
          if [ -z "$PUB" ]; then PUB="${{ vars.PUBLIC_SUBSTACK_URL }}"; fi
          if [ -z "$PUB" ]; then PUB="https://versesvibez.substack.com/"; fi
          echo "PUBLIC_SUBSTACK_URL=$PUB" >> "$GITHUB_ENV"

          # Proxy (BEST: your Cloudflare Worker). TEMP fallback: rss2json public API.
          PROXY="${RSS_PROXY_URL:-${{ secrets.RSS_PROXY_URL }}}"
          if [ -z "$PROXY" ]; then PROXY="${{ vars.RSS_PROXY_URL }}"; fi
          if [ -z "$PROXY" ]; then PROXY="https://api.rss2json.com/v1/api.json?rss_url="; fi
          echo "RSS_PROXY_URL=$PROXY" >> "$GITHUB_ENV"

      - name: Build site (templating only)
        run: python fetch.py

      - name: Verify dist exists
        run: test -d dist && ls -la dist

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
